// https://projecteuler.net/problem=29

/*
How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
*/

export const distinctPowers = (limit = 100) => {
  if (limit < 2) throw new Error('Power out of scope')
  // A Set data structure to keep track of distinct powers
  let distinctPowerSet = new Set()
  for (let a = 2; a <= limit; a++) {
    for (let b = 2; b <= limit; b++) {
      distinctPowerSet.add(Math.pow(a, b))
    }
  }
  return distinctPowerSet.size
}
