/**
 *
 * Project Euler 2
 *
 * Each new term in the Fibonacci sequence
 * is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 */

const SQ5 = 5 ** 0.5
// Square root of 5

const PHI = (1 + SQ5) / 2
// definition of PHI

// theoretically it should take O(1) constant amount of time as long
// arithmetic calculations are considered to be in constant amount of time
function EvenFibonacci (limit) {
  const highestIndex = Math.floor(Math.log(limit * SQ5) / Math.log(PHI))
  const n = Math.floor(highestIndex / 3)
  return (
    ((PHI ** (3 * n + 3) - 1) / (PHI ** 3 - 1) -
      ((1 - PHI) ** (3 * n + 3) - 1) / ((1 - PHI) ** 3 - 1)) /
    SQ5
  )
}
console.log(EvenFibonacci(4e6))
// Sum of Even Fibonnaci upto 4 Million

// Alternative Solution
// const evenFibonnaciSum = (n) => {
//   let fib = [1, 2]
//   for (let i = 2; i < n; i++) {
//     fib[i] = fib[i - 1] + fib[i - 2]
//   }

//   return fib
// }

// const sum = evenFibonnaciSum(100)
//   .filter((i) => i < 4000000 && i % 2 === 0)
//   .reduce((a, b) => a + b, 0)

// console.log(sum)
