/**
 * Problem - Distinct Powers
 *
 * Find the number of distinct terms generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.
 */

/**
 * Main function to count distinct powers a^b.
 *
 * @param {number} minA
 * @param {number} maxA
 * @param {number} minB
 * @param {number} maxB
 * @returns {number}
 */
function countDistinctPowers(minA, maxA, minB, maxB) {
  /**
   * Set to store distinct terms generated by a^b.
   */
  const distinctTerms = new Set()

  for (let a = minA; a <= maxA; a++) {
    for (let b = minB; b <= maxB; b++) {
      distinctTerms.add(Math.pow(a, b))
    }
  }

  return distinctTerms.size
}

const minA = 2
const maxA = 100
const minB = 2
const maxB = 100

const result = countDistinctPowers(minA, maxA, minB, maxB)
console.log(`Number of distinct terms: ${result}`)

export { countDistinctPowers }
