/*
  Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/


function isPentagonal(n) {
  const pent = (Math.sqrt(24 * n + 1) + 1) / 6
  return pent === Math.floor(pent)
}

function getResult() {
  let result = 0
  let notFound = true
  let i = 1

  while (notFound) {
      i++
      let n = i * (3 * i - 1) / 2 //Apply formula

      for (let j = i-1; j > 0; j--) {
          let m = j * (3 * j - 1) / 2 //Check rest of list
          //Verify numers result
          if (isPentagonal(n - m) && isPentagonal(n + m)) {
              result = n-m
              notFound = false
              break
          }
      }
  }
  
  return result
}




