/**
 *
 * Project Euler 2
 *
 * Each new term in the Fibonacci sequence
 * is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million,
 * find the sum of the even-valued terms.
 */

// Alternative Solution
const evenFibonnaciSum = (n) => {
  const fib = [1, 2]
  for (let i = 2; i < n; i++) {
    fib[i] = fib[i - 1] + fib[i - 2]
  }

  return fib
}

const sum = evenFibonnaciSum(100)
  .filter((i) => i < 4000000 && i % 2 === 0)
  .reduce((a, b) => a + b, 0)

console.log(sum)
