/*
Problem statement:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
*/
var n = 4000000; // For problem 2 in projecteuler.net, N=4000000
var sum = 0;
var i = 1;
var j = 1;
while(i <= n) {
    var k = i+j;
    if(k%2==0) sum += k
    j = i;
    i = k;
}
console.log(sum);
